import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import localFont from "next/font/local";

import type React from "react";

const primaryFont = localFont({
	src: [
		{
			path: "../public/fonts/Italian-Plate-No2-Expanded-Extrabold.ttf",
			weight: "800",
			style: "normal",
		},
		{
			path: "../public/fonts/Italian-Plate-No2-Expanded-Bold.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "../public/fonts/Italian-Plate-No2-Expanded-Demibold.ttf",
			weight: "600",
			style: "normal",
		},
		{
			path: "../public/fonts/Italian-Plate-No2-Expanded-Medium.ttf",
			weight: "500",
			style: "normal",
		},
	],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={primaryFont.className}>
			<body
			// className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
